displayName: ESA_LIGHT_1
schemaName: crc1d_agentB3vfwx
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

  settings:
    GenerativeActionsEnabled: false

  isAgentConnectable: false
  publishOnImport: false
  gPTSettings:
    defaultSchemaName: crc1d_agentB3vfwx.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: false
    isSemanticSearchEnabled: true
    contentModeration: Low
    optInUseLatestModels: false

publishedOn: 2026-06-17T15:34:04.0000000Z
template: default-2.1.0
language: 1033