displayName: ESATEST15
schemaName: crc1d_agentB3vfwx
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  publishOnImport: false
  gPTSettings:
    defaultSchemaName: crc1d_agentB3vfwx.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    contentModeration: Low
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-06-12T18:33:21.0000000Z
template: default-2.1.0
language: 1033